services:
  - type: web
    name: fix-your-english
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.webapp.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false 